(function(v,d,l,o,R){"use strict";var h=null,f=null,c=[],y=new Map,F=new Set;function g(t){return t&&typeof t.content=="string"?t.content:""}function A(t,a){var e;try{var n=d.findByProps("getMessage","getMessages")||d.findByProps("_channelMessages");if(n&&n.getMessage)return n.getMessage(t,a);if(n&&n._channelMessages)return(e=n._channelMessages.get(t))==null?void 0:e.get(a)}catch(u){}return null}function E(t,a){return{backgroundColor:l.ReactNative.processColor(t),gutterColor:l.ReactNative.processColor(a)}}function M(t){var a=`

[\u5DF2\u7F16\u8F91]
`,e=t.lastIndexOf(a);return e>=0?t.slice(e+a.length):t}function w(){var t=d.findByProps("updateRows","getConstants")||d.findByProps("updateRows");return!t||!t.updateRows?null:o.before("updateRows",t,function(a){try{var e=a[1],n=typeof e=="string",u=n?JSON.parse(e):e;if(!Array.isArray(u))return;for(var s=0;s<u.length;s++){var r=u[s],i=r&&r.message;if(i){var p=String(i.id||"");i.was_deleted||y.has(p)?(i.textColor=l.ReactNative.processColor("#F23F43"),r.backgroundHighlight=E("#4B1F25","#F23F43")):F.has(p)&&(i.textColor=l.ReactNative.processColor("#5865F2"),r.backgroundHighlight=E("#1E3656","#5865F2"))}}a[1]=n?JSON.stringify(u):u}catch(_){console.error("[AntiRecall] row patch",_)}})}function D(){var t=d.findByProps("updateMessageRecord","createMessageRecord");if(t){try{c.push(o.after("createMessageRecord",t,function(e,n){e[0]&&e[0].was_deleted&&n&&(n.was_deleted=!0)}))}catch(e){}try{var a=d.findByName("MessageRecord",!1);a&&c.push(o.after("default",a,function(e,n){e[0]&&e[0].was_deleted&&n&&(n.was_deleted=!0)}))}catch(e){}try{c.push(o.instead("updateMessageRecord",t,function(e,n){var u=e[0],s=e[1];return s&&s.was_deleted?t.createMessageRecord(s,u&&u.reactions):n.apply(this,e)}))}catch(e){}}}function S(){var t=l.FluxDispatcher||d.findByProps("dispatch","subscribe");return!t||!t.dispatch?null:o.before("dispatch",t,function(a){try{var e=a[0];if(!e||e.otherPluginBypass)return;if(e.type==="MESSAGE_DELETE"){var n=A(e.channelId||e.channel_id,e.id||e.message_id);if(!n)return;var u=g(n);y.set(String(n.id),!0),e.message=Object.assign({},n,{channel_id:n.channel_id||e.channelId||e.channel_id,guild_id:n.guild_id||e.guildId||e.guild_id,content:u.indexOf(`[\u5DF2\u64A4\u56DE]
`)===0?u:`[\u5DF2\u64A4\u56DE]
`+(u||"(\u65E0\u6587\u5B57\u5185\u5BB9)"),was_deleted:!0,edited_timestamp:"invalid_timestamp"}),e.type="MESSAGE_UPDATE",e.channelId=n.channel_id||e.channelId||e.channel_id,e.optimistic=!1,e.sendMessageOptions={}}else if(e.type==="MESSAGE_UPDATE"){var s=e.message,r=s&&(s.channel_id||e.channelId||e.channel_id),i=s&&A(r,s.id);if(!i||g(i)===g(s))return;var p=g(i),_=M(g(s));F.add(String(s.id)),e.message=Object.assign({},s,{content:M(p)+`

[\u5DF2\u7F16\u8F91]
`+_})}}catch(b){console.error("[AntiRecall] dispatch patch",b)}})}function B(){h=S(),f=w(),D();try{R.showToast("AntiRecall v3 \u5DF2\u542F\u52A8\uFF1A\u64A4\u56DE\u7EA2\u6846\u3001\u7F16\u8F91\u84DD\u6846\uFF08\u91CD\u542F\u6E05\u7A7A\uFF09")}catch(t){}}function C(){try{h&&h()}catch(a){}try{f&&f()}catch(a){}for(var t=0;t<c.length;t++)try{c[t]()}catch(a){}h=null,f=null,c=[],y.clear(),F.clear()}return v.onLoad=B,v.onUnload=C,v})({},vendetta.metro,vendetta.metro.common,vendetta.patcher,vendetta.ui.toasts);
